### PR TITLE
Updated to latest versions and compatibility

### PR DESCRIPTION
**Pull request by alecdewitz**

### CODE REVIEW

**Comment by REPTILEHAUS** [comment]
Awesome. Thanks for Contributing man!

**Comment by alecdewitz** [comment]
No problem 😎

**Comment by REPTILEHAUS** [comment]
looks like you removed this though - in the home template

```
<app-chat></app-chat> 
```

**Comment by alecdewitz** [comment]
It’s in app component

**Comment by REPTILEHAUS** [comment]
I tried to run the project and got some errors related to the home template. basically it wouldnt start up

**Comment by alecdewitz** [comment]
Ok I will retest tonight

**Comment by alecdewitz** [comment]
Was working for me last night :(

**Comment by REPTILEHAUS** [comment]
No worries looks like a simple fix - the router is pointing to the home template but that template is now blank whereas before it contained the chat components selector. Let me know if you do it if not ill revert

**Pull request merged**
